/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/api/health': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns the health status of the Platform API
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['HealthResponse'];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/apps/{appId}/deploy': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deploy app script
         * @description Deploy app code to Cloudflare Workers for Platforms. Send bundle as multipart/form-data with optional metadata and asset manifest.
         */
        post: {
            parameters: {
                query?: {
                    /** @description Target environment */
                    env?: 'production' | 'preview';
                };
                header?: never;
                path: {
                    /** @description Unique app identifier */
                    appId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    'multipart/form-data': string;
                    'application/octet-stream': string;
                };
            };
            responses: {
                /** @description Deployment successful */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['DeployResult'];
                    };
                };
                /** @description Invalid request (empty bundle, bundle too large, invalid parameters) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ErrorResponse'];
                    };
                };
                /** @description Authentication failed (missing or invalid token) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ErrorResponse'];
                    };
                };
                /** @description Permission denied */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ErrorResponse'];
                    };
                };
                /** @description App not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ErrorResponse'];
                    };
                };
                /** @description Cloudflare deployment failed */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ErrorResponse'];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/apps/{appId}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get app deployment status
         * @description Get app deployment status for production and preview environments
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Unique app identifier */
                    appId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description App status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['AppStatus'];
                    };
                };
                /** @description Authentication failed */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ErrorResponse'];
                    };
                };
                /** @description App not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ErrorResponse'];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Remove app script
         * @description Remove app script from Cloudflare Workers for Platforms. Optionally delete associated data.
         */
        delete: {
            parameters: {
                query?: {
                    /** @description Target environment */
                    env?: 'production' | 'preview';
                    /** @description Permanently delete all associated data */
                    deleteData?: boolean;
                };
                header?: never;
                path: {
                    /** @description Unique app identifier */
                    appId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Undeploy successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['UndeployResult'];
                    };
                };
                /** @description Invalid parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ErrorResponse'];
                    };
                };
                /** @description Authentication failed */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ErrorResponse'];
                    };
                };
                /** @description Permission denied */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ErrorResponse'];
                    };
                };
                /** @description App not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ErrorResponse'];
                    };
                };
                /** @description Cloudflare undeploy failed */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ErrorResponse'];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/apps/{appId}/logs': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get recent app logs
         * @description Query recent app logs for a deployed app
         */
        get: {
            parameters: {
                query?: {
                    since?: string;
                    until?: string;
                    /** @description Return the newest N rows after filters */
                    last?: number;
                    /** @description Environment filter */
                    env?: 'production' | 'preview';
                    /** @description Optional handler filter */
                    handler?: 'web' | 'events';
                    /** @description Cloudflare worker outcome filter */
                    outcome?: components['schemas']['LogOutcome'];
                    /** @description Optional HTTP status code filter */
                    statusCode?: number;
                };
                header?: never;
                path: {
                    /** @description Unique app identifier */
                    appId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Recent app logs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['LogsResponse'];
                    };
                };
                /** @description Invalid logs query */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ErrorResponse'];
                    };
                };
                /** @description Authentication failed */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ErrorResponse'];
                    };
                };
                /** @description Permission denied */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ErrorResponse'];
                    };
                };
                /** @description App not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ErrorResponse'];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/apps/{appId}/secrets': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List secrets
         * @description List all secret names for the app
         */
        get: {
            parameters: {
                query?: {
                    /** @description Target environment */
                    env?: 'production' | 'preview';
                };
                header?: never;
                path: {
                    /** @description Unique app identifier */
                    appId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Secrets list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['SecretsListResponse'];
                    };
                };
                /** @description Authentication failed */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ErrorResponse'];
                    };
                };
                /** @description Permission denied */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ErrorResponse'];
                    };
                };
                /** @description App not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ErrorResponse'];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/apps/{appId}/secrets/{name}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set secret
         * @description Set a secret value for the app
         */
        put: {
            parameters: {
                query?: {
                    /** @description Target environment */
                    env?: 'production' | 'preview';
                };
                header?: never;
                path: {
                    /** @description Unique app identifier */
                    appId: string;
                    /** @description Secret name */
                    name: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    'application/json': components['schemas']['SecretValueRequest'];
                };
            };
            responses: {
                /** @description Secret set successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['SecretResponse'];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ErrorResponse'];
                    };
                };
                /** @description Authentication failed */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ErrorResponse'];
                    };
                };
                /** @description Permission denied */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ErrorResponse'];
                    };
                };
                /** @description App not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ErrorResponse'];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete secret
         * @description Delete a secret from the app
         */
        delete: {
            parameters: {
                query?: {
                    /** @description Target environment */
                    env?: 'production' | 'preview';
                };
                header?: never;
                path: {
                    /** @description Unique app identifier */
                    appId: string;
                    /** @description Secret name */
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Secret deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['SecretResponse'];
                    };
                };
                /** @description Authentication failed */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ErrorResponse'];
                    };
                };
                /** @description Permission denied */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ErrorResponse'];
                    };
                };
                /** @description App or secret not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ErrorResponse'];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: 'ok';
            /** @example prod */
            environment: string;
            /**
             * Format: date-time
             * @example 2024-01-15T12:00:00.000Z
             */
            timestamp: string;
        };
        DeployResult: {
            /** @enum {boolean} */
            success: true;
            /**
             * Format: uri
             * @example https://my-app.bkper.app
             */
            url: string;
            /** @enum {string} */
            environment: 'production' | 'preview';
            /** @example bkper-apps-prod */
            namespace: string;
            /** @example my-app-123 */
            scriptName: string;
            /**
             * Format: date-time
             * @example 2024-01-15T12:00:00.000Z
             */
            updatedAt: string;
            /** @description Provisioned bindings with their types */
            bindings?: Array<{ name: string; type: string }>;
        };
        ErrorResponse: {
            /** @enum {boolean} */
            success: false;
            error: {
                /** @example INVALID_TOKEN */
                code: string;
                /** @example Invalid or expired token */
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        UndeployResult: {
            /** @enum {boolean} */
            success: true;
            /** @example App 'my-app' removed from production */
            message: string;
            /** @example bkper-apps-prod */
            namespace: string;
            /** @example my-app-123 */
            scriptName: string;
            /** @description Whether associated data was deleted */
            dataDeleted?: boolean;
            /** @description Names of deleted bindings */
            deletedBindings?: string[];
        };
        AppStatus: {
            appId: string;
            prod: components['schemas']['ScriptStatus'];
            preview: components['schemas']['ScriptStatus'];
        };
        ScriptStatus: {
            deployed: boolean;
            /** Format: uri */
            url: string;
            scriptName: string;
            namespace: string;
            /** Format: date-time */
            updatedAt?: string;
        } | null;
        /** @enum {string} */
        LogOutcome:
            | 'unknown'
            | 'ok'
            | 'exception'
            | 'exceededCpu'
            | 'exceededMemory'
            | 'scriptNotFound'
            | 'canceled'
            | 'responseStreamDisconnected';
        LogException: {
            /** @example Error */
            name: string;
            /** @example Webhook failed */
            message: string;
            /** @example Error: Webhook failed\n    at ... */
            stack?: string;
        };
        LogEntry: {
            /** Format: date-time */
            timestamp: string;
            environment: 'production' | 'preview';
            handler: 'web' | 'events';
            outcome: components['schemas']['LogOutcome'];
            requestMethod: string | null;
            requestUrl: string | null;
            statusCode: number | null;
            logs: string[];
            exceptions: components['schemas']['LogException'][];
        };
        LogsMeta: {
            last: number;
            retentionDays: number;
            warnings: string[];
        };
        LogsResponse: {
            logs: components['schemas']['LogEntry'][];
            meta: components['schemas']['LogsMeta'];
        };
        SecretsListResponse: {
            secrets: string[];
            environment: 'production' | 'preview';
        };
        SecretValueRequest: {
            value: string;
        };
        SecretResponse: {
            /** @enum {boolean} */
            success: true;
            name: string;
            environment: 'production' | 'preview';
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
