/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns the health status of the Platform API
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{appId}/deploy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deploy app script
         * @description Deploy app code to Cloudflare Workers for Platforms. The request body should contain the bundled JavaScript code.
         */
        post: {
            parameters: {
                query?: {
                    /** @description Target environment */
                    env?: "prod" | "dev";
                    /** @description Deployment type (web handler or events handler) */
                    type?: "web" | "events";
                };
                header?: never;
                path: {
                    /** @description Unique app identifier */
                    appId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/octet-stream": string;
                };
            };
            responses: {
                /** @description Deployment successful */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeployResult"];
                    };
                };
                /** @description Invalid request (empty bundle, bundle too large, invalid parameters) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Authentication failed (missing or invalid token) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Permission denied */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description App not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Cloudflare deployment failed */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{appId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get app deployment status
         * @description Get the deployment status for all environments and types of an app
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Unique app identifier */
                    appId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description App status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AppStatus"];
                    };
                };
                /** @description Authentication failed */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description App not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Remove app script
         * @description Remove app script from Cloudflare Workers for Platforms
         */
        delete: {
            parameters: {
                query?: {
                    /** @description Target environment */
                    env?: "prod" | "dev";
                    /** @description Deployment type (web handler or events handler) */
                    type?: "web" | "events";
                };
                header?: never;
                path: {
                    /** @description Unique app identifier */
                    appId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Undeploy successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UndeployResult"];
                    };
                };
                /** @description Invalid parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Authentication failed */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Permission denied */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description App not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Cloudflare undeploy failed */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
            /** @example prod */
            environment: string;
            /**
             * Format: date-time
             * @example 2024-01-15T12:00:00.000Z
             */
            timestamp: string;
        };
        DeployResult: {
            /** @enum {boolean} */
            success: true;
            /**
             * Format: uri
             * @example https://my-app.bkper.app
             */
            url: string;
            /** @enum {string} */
            environment: "prod" | "dev";
            /** @enum {string} */
            type: "web" | "events";
            /** @example bkper-apps-prod */
            namespace: string;
            /** @example my-app-123 */
            scriptName: string;
            /**
             * Format: date-time
             * @example 2024-01-15T12:00:00.000Z
             */
            updatedAt: string;
        };
        ErrorResponse: {
            /** @enum {boolean} */
            success: false;
            error: {
                /** @example INVALID_TOKEN */
                code: string;
                /** @example Invalid or expired token */
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        UndeployResult: {
            /** @enum {boolean} */
            success: true;
            /** @example App 'my-app' web handler removed from prod */
            message: string;
            /** @example bkper-apps-prod */
            namespace: string;
            /** @example my-app-123 */
            scriptName: string;
        };
        AppStatus: {
            appId: string;
            prod: components["schemas"]["EnvStatus"];
            dev: components["schemas"]["EnvStatus"];
        };
        EnvStatus: {
            web: components["schemas"]["ScriptStatus"];
            events: components["schemas"]["ScriptStatus"];
        };
        ScriptStatus: {
            deployed: boolean;
            /** Format: uri */
            url: string;
            scriptName: string;
            namespace: string;
            /** Format: date-time */
            updatedAt?: string;
        } | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
