/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns the health status of the Platform API
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{appId}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get recent app logs
         * @description Query recent app logs for a deployed app
         */
        get: {
            parameters: {
                query?: {
                    /** @description ISO8601 timestamp or relative duration like 5m, 1h, or 15d */
                    since?: string;
                    /** @description ISO8601 timestamp or relative duration like 5m, 1h, or 15d */
                    until?: string;
                    /** @description Return the newest N requests after filters */
                    last?: number;
                    /** @description Environment filter */
                    env?: "production" | "preview";
                    /** @description Optional handler filter */
                    handler?: components["schemas"]["LogHandlerType"] & unknown;
                    /** @description Minimum log level threshold. info returns info/warn/error, warn returns warn/error, error returns error only. */
                    level?: components["schemas"]["LogLevel"] & unknown;
                    /** @description Optional HTTP status code filter */
                    statusCode?: number | null;
                };
                header?: never;
                path: {
                    /** @description Unique app identifier */
                    appId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Recent app logs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogsResponse"];
                    };
                };
                /** @description Invalid logs query */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Authentication failed */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Permission denied */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description App not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Logs backend failed */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{appId}/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get managed source status
         * @description Returns the Platform-owned source linkage for an authorized App developer. A not-managed result is eventually consistent and does not migrate existing external, no-remote, or monorepo Apps.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Unique app identifier */
                    appId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Managed source status. Negative lookups are eventually consistent. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ManagedSourceStatus"];
                    };
                };
                /** @description Invalid managed source state */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Authentication failed */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Permission denied */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description App not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Managed source linkage mismatch */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Managed source adapter failed */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Managed source disabled */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{appId}/source/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate owner-bound managed source
         * @description Creates or safely resumes one private repository from a UUID-v4 activation claim. Platform derives ownerId from the trusted Core App and never accepts client-supplied ownership.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Unique app identifier */
                    appId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ActivateManagedSourceBody"];
                };
            };
            responses: {
                /** @description Existing source resumed or adopted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ManagedSourceActivationResult"];
                    };
                };
                /** @description Managed source created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ManagedSourceActivationResult"];
                    };
                };
                /** @description Invalid activation ID */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Authentication failed */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Permission denied */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description App not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Collision or ownership mismatch */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Artifacts adapter failed */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Managed source disabled */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{appId}/source/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a five-minute repository credential
         * @description Issues a short-lived read or write credential for the exact Platform-linked repository. Configured developers, including domain-pattern matches, use the existing App developer authorization. Credentials are not cacheable.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Unique app identifier */
                    appId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ManagedSourceCredentialBody"];
                };
            };
            responses: {
                /** @description Short-lived credential */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ManagedSourceCredentialResult"];
                    };
                };
                /** @description Invalid scope */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Authentication failed */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Permission denied */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description App not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Managed source missing or mismatched */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Artifacts adapter failed */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Managed source disabled */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{appId}/deploy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deploy app script
         * @description Explicitly uploads an existing local bundle to Cloudflare Workers for Platforms; this endpoint never builds from Git and Git pushes never deploy. When Platform observes managed source, metadata must declare a full commit SHA and attached branch. Platform verifies that exact commit in its linked repository before upload, but does not claim that the local bundle was reproducibly built from it. External Apps retain source-less direct uploads.
         */
        post: {
            parameters: {
                query?: {
                    /** @description Target environment */
                    env?: "production" | "preview";
                    /** @description JSON-encoded bindings from CLI (alternative to multipart metadata) */
                    bindings?: string;
                };
                header?: never;
                path: {
                    /** @description Unique app identifier */
                    appId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": unknown;
                    "application/octet-stream": unknown;
                };
            };
            responses: {
                /** @description Deployment successful */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeployResult"];
                    };
                };
                /** @description Invalid request (empty bundle, bundle too large, invalid parameters) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Authentication failed (missing or invalid token) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Permission denied */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description App not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Managed source linkage requires a source-aware client */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Feature not implemented */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Cloudflare deployment failed */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Managed source disabled */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{appId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get app deployment status
         * @description Get active production and preview runtime status. Managed runtimes include the exact verified repository SHA plus the developer-declared branch and actor; no deployment history is retained.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Unique app identifier */
                    appId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description App status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AppStatus"];
                    };
                };
                /** @description Authentication failed */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description App not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Remove app script
         * @description Remove app script from Cloudflare Workers for Platforms. Optionally delete associated data (KV namespaces, etc.).
         */
        delete: {
            parameters: {
                query?: {
                    /** @description Target environment */
                    env?: "production" | "preview";
                    /** @description Also delete associated resources (KV namespaces, etc.) */
                    deleteData?: boolean | null;
                };
                header?: never;
                path: {
                    /** @description Unique app identifier */
                    appId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Undeploy successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UndeployResult"];
                    };
                };
                /** @description Invalid parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Authentication failed */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Permission denied */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description App not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Cloudflare undeploy failed */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{appId}/secrets/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set a secret
         * @description Set a secret for an app. The secret is stored encrypted and set on the app Worker.
         */
        put: {
            parameters: {
                query?: {
                    /** @description Target environment */
                    env?: "production" | "preview";
                };
                header?: never;
                path: {
                    /** @description Unique app identifier */
                    appId: string;
                    /** @description Secret name (valid identifier) */
                    name: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SecretValue"];
                };
            };
            responses: {
                /** @description Secret set successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PutSecretResult"];
                    };
                };
                /** @description Invalid request (invalid secret name, scripts not deployed) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Authentication failed */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Permission denied */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description App not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Cloudflare API failed */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete a secret
         * @description Delete a secret from the app Worker.
         */
        delete: {
            parameters: {
                query?: {
                    /** @description Target environment */
                    env?: "production" | "preview";
                };
                header?: never;
                path: {
                    /** @description Unique app identifier */
                    appId: string;
                    /** @description Secret name (valid identifier) */
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Secret deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeleteSecretResult"];
                    };
                };
                /** @description Invalid request (invalid secret name) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Authentication failed */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Permission denied */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description App not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Cloudflare API failed */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/{appId}/secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List secrets
         * @description List secret names for an app. Values are not returned for security.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Target environment */
                    env?: "production" | "preview";
                };
                header?: never;
                path: {
                    /** @description Unique app identifier */
                    appId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Secret names */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListSecretsResult"];
                    };
                };
                /** @description Invalid request (scripts not deployed) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Authentication failed */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Permission denied */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description App not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Cloudflare API failed */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
            /** @example production */
            environment: string;
            /**
             * Format: date-time
             * @example 2024-01-15T12:00:00.000Z
             */
            timestamp: string;
        };
        LogsResponse: {
            logs: components["schemas"]["LogEntry"][];
            meta: components["schemas"]["LogsMeta"];
        };
        LogEntry: {
            /**
             * Format: date-time
             * @example 2026-04-29T12:00:00.000Z
             */
            timestamp: string;
            /** @enum {string} */
            environment: "production" | "preview";
            handler: components["schemas"]["LogHandlerType"];
            level: components["schemas"]["LogLevel"];
            outcome: components["schemas"]["LogOutcome"];
            /** @example POST */
            requestMethod: string | null;
            /** @example https://my-app.bkper.app/events */
            requestUrl: string | null;
            /** @example 500 */
            statusCode: number | null;
            /**
             * @example [
             *       {
             *         "level": "info",
             *         "message": "Processing webhook..."
             *       },
             *       {
             *         "level": "error",
             *         "name": "Error",
             *         "message": "Webhook failed",
             *         "stack": "Error: Webhook failed\n    at ..."
             *       }
             *     ]
             */
            entries: components["schemas"]["LogLineEntry"][];
        };
        /** @enum {string} */
        LogHandlerType: "web" | "events";
        /** @enum {string} */
        LogLevel: "info" | "warn" | "error";
        /** @enum {string} */
        LogOutcome: "unknown" | "ok" | "exception" | "exceededCpu" | "exceededMemory" | "scriptNotFound" | "canceled" | "responseStreamDisconnected";
        LogLineEntry: {
            level: components["schemas"]["LogLevel"];
            /** @example Processing webhook... */
            message: string;
            /** @example Error */
            name?: string;
            /**
             * @example Error: Webhook failed
             *         at ...
             */
            stack?: string;
        };
        LogsMeta: {
            /** @example 100 */
            last: number;
            /** @example 15 */
            retentionDays: number;
            /**
             * @example [
             *       "since was clamped to the 15-day retention window"
             *     ]
             */
            warnings: string[];
        };
        ErrorResponse: {
            /** @enum {boolean} */
            success: false;
            error: {
                /** @example INVALID_TOKEN */
                code: string;
                /** @example Invalid or expired token */
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        ManagedSourceStatus: {
            /** @enum {string} */
            mode: "external";
            /** @enum {string} */
            state: "not_managed";
            /** @enum {string} */
            consistency: "eventual";
            /**
             * @description Negative KV lookups are eventually consistent; managed-aware clients retry rather than silently downgrade.
             * @enum {boolean}
             */
            retryable: true;
        } | {
            /** @enum {string} */
            mode: "managed";
            /** @enum {string} */
            state: "active";
            /** @enum {string} */
            consistency: "eventual";
            appId: string;
            repositoryId: string;
            repositoryName: string;
            namespace: string;
            /** Format: uri */
            remote: string;
        };
        ManagedSourceActivationResult: {
            /** @enum {boolean} */
            success: true;
            /** @enum {string} */
            disposition: "created" | "adopted" | "existing";
            source: {
                /** @enum {string} */
                mode: "managed";
                appId: string;
                repositoryId: string;
                repositoryName: string;
                namespace: string;
                /** Format: uri */
                remote: string;
            };
        };
        ActivateManagedSourceBody: {
            /**
             * @description Stable repository-local activation claim. Ownership is resolved from the trusted Core App.
             * @example 28fbf7de-9755-4bb3-a263-0227b2a2696b
             */
            activationId: string;
        };
        ManagedSourceCredentialResult: {
            /** @description Sensitive short-lived repository credential. Never persist, log, fixture, or expose this value. */
            token: string;
            /** @enum {string} */
            scope: "read" | "write";
            /** Format: date-time */
            expiresAt: string;
            /** Format: uri */
            remote: string;
        };
        ManagedSourceCredentialBody: {
            /**
             * @description Repository scope. Credentials are exact-repository scoped and expire after five minutes.
             * @enum {string}
             */
            scope: "read" | "write";
        };
        DeployResult: {
            /** @enum {boolean} */
            success: true;
            /**
             * Format: uri
             * @example https://my-app.bkper.app
             */
            url: string;
            /** @enum {string} */
            environment: "production" | "preview";
            /** @example bkper-apps-prod */
            namespace: string;
            /** @example my-app-123 */
            scriptName: string;
            /**
             * Format: date-time
             * @example 2024-01-15T12:00:00.000Z
             */
            updatedAt: string;
            /** @description Provisioned bindings with their types */
            bindings?: {
                name: string;
                type: string;
            }[];
            source?: components["schemas"]["ActiveDeploymentSource"];
        };
        /** @description Active managed-source provenance. The SHA exists in the linked repository; the branch and local-build relationship are developer-declared. */
        ActiveDeploymentSource: {
            /** @enum {string} */
            mode: "managed";
            verifiedSha: string;
            declaredBranch: string;
            actorId: string;
        };
        UndeployResult: {
            /** @enum {boolean} */
            success: true;
            /** @example App 'my-app' removed from production */
            message: string;
            /** @example bkper-apps-prod */
            namespace: string;
            /** @example my-app-123 */
            scriptName: string;
            /** @description Whether associated data was deleted */
            dataDeleted?: boolean;
            /** @description Names of deleted bindings */
            deletedBindings?: string[];
        };
        AppStatus: {
            appId: string;
            prod: components["schemas"]["ScriptStatus"];
            preview: components["schemas"]["ScriptStatus"];
        };
        ScriptStatus: {
            deployed: boolean;
            /** Format: uri */
            url: string;
            scriptName: string;
            namespace: string;
            /** Format: date-time */
            updatedAt?: string;
            source?: components["schemas"]["ActiveDeploymentSource"] & unknown;
        } | null;
        PutSecretResult: {
            /** @enum {boolean} */
            success: true;
            /** @example DATABASE_URL */
            name: string;
            /** @enum {string} */
            environment: "production" | "preview";
        };
        SecretValue: {
            /**
             * @description The secret value
             * @example my-secret-value
             */
            value: string;
        };
        ListSecretsResult: {
            /**
             * @description List of secret names (values are not returned)
             * @example [
             *       "DATABASE_URL",
             *       "API_KEY"
             *     ]
             */
            secrets: string[];
            /** @enum {string} */
            environment: "production" | "preview";
        };
        DeleteSecretResult: {
            /** @enum {boolean} */
            success: true;
            /** @example DATABASE_URL */
            name: string;
            /** @enum {string} */
            environment: "production" | "preview";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
